//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLBackup.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Bağlantı (Connection String).
        /// </summary>
        internal static string Baglanti {
            get {
                return ResourceManager.GetString("Baglanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Kolay Yedekleme.
        /// </summary>
        internal static string Baslik {
            get {
                return ResourceManager.GetString("Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüş ve Öneri.
        /// </summary>
        internal static string GorusOneri {
            get {
                return ResourceManager.GetString("GorusOneri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet ve Başlat.
        /// </summary>
        internal static string KaydetBaslat {
            get {
                return ResourceManager.GetString("KaydetBaslat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planan Saat.
        /// </summary>
        internal static string PlanlananSaat {
            get {
                return ResourceManager.GetString("PlanlananSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlanan Saatler.
        /// </summary>
        internal static string PlanlananSaatler {
            get {
                return ResourceManager.GetString("PlanlananSaatler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h&apos;sa &apos;m&apos;dk &apos;s&apos;s&apos;.
        /// </summary>
        internal static string SaatFormati {
            get {
                return ResourceManager.GetString("SaatFormati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string SQLKullaniciAdi {
            get {
                return ResourceManager.GetString("SQLKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string SQLSifre {
            get {
                return ResourceManager.GetString("SQLSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Dili.
        /// </summary>
        internal static string UygulamaDili {
            get {
                return ResourceManager.GetString("UygulamaDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı.
        /// </summary>
        internal static string Veritabani {
            get {
                return ResourceManager.GetString("Veritabani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Sunucusu.
        /// </summary>
        internal static string VeritabaniSunucusu {
            get {
                return ResourceManager.GetString("VeritabaniSunucusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yedekleme için kalan süre.
        /// </summary>
        internal static string YedeklemeicinKalanSure {
            get {
                return ResourceManager.GetString("YedeklemeicinKalanSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yedeklenecek Lokasyon.
        /// </summary>
        internal static string YedeklenecekLokasyon {
            get {
                return ResourceManager.GetString("YedeklenecekLokasyon", resourceCulture);
            }
        }
    }
}
